# This may be very slow.
# https://unix.stackexchange.com/questions/22979/path-helper-and-zsh
# If the path_helper tool exists (i.e. on a Mac) then run it.
# if [ -f "/usr/libexec/path_helper" ]; then
#     eval $(/usr/libexec/path_helper -s)
# fi

# ZSH completion.
# This seems to be essential but *very* slow and needs debugging.
# fpath=(~/.zsh/completion $fpath)
# autoload -Uz compinit && compinit -i

# Source my personal (github.com/dwmkerr/dotfiles) configuration.
[ -r ~/.shell.sh ] && source ~/.shell.sh
